### ISSUE TITLE
[FEATURE] Define own itemset

### ISSUE THREAD

**Issue by Dreandor** [Despical/OITC#13]
Hey mate,
would it be possible to set your own items as starting items? So e.g. via config that you can only play with a bow in one arena and with a sword in the other arena, for example.

**Comment by Despical** [comment]
Hey buddy, it's good to see you again and yeah, I can add something like that.

**Comment by Despical** [comment]
Now kits can be customizable based on different arenas.

```yaml
kits:
  # If an arena does not have a kit, the default kit will be given.
  # Change 'default' to arena id to create custom kits for different arenas.
  default:
    # Slot of the item.
    '0':
      material: WOODEN_SWORD
      name: "&7Sword"
      lore: []
    '1':
      material: BOW
      lore: []
      enchantments:
        - "LUCK:1"
      item-flags:
        - "HIDE_ENCHANTS"
    '7':
      material: ARROW
      name: "&7Arrow"
      lore: []

  # 'example-kit-1' is the arena id (not map name).
  example-kit-1:
    # Slot of the item.
    '0':
      material: DIAMOND_SWORD
      name: "&b&lDiamond Sword"
      lore: []
    '1':
      material: BOW
      lore: []
      enchantments:
        - "LUCK:1"
      item-flags:
        - "HIDE_ENCHANTS"
    '7':
      material: ARROW
      name: "&7Arrow"
      lore: []
```
